--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/STogkGamemodeUI
build-by-default: true
branches:
- main
projects:
  STogkGamemodeUI:
    icon: "icon.png"
    path: ""
...
