---
name: STogkGamemodeUI
main: Angga7Togk\STogkGamemodeUI\Main
version: 1.0
api: 4.0.0
author: Angga7Togk
description: "Open The STogkGamemodeUI"

commands:
  gmdui:
    description: "Open The STogkGamemodeUI"
    permission: gamemodeui.use

permissions:
  gamemodeui.use:
    description: STogkGamemodeUI Permission
    default: op
  gamemodeui.use.creative:
    description: STogkGamemodeUI Creative Permission
    default: op
  gamemodeui.use.survival:
    description: STogkGamemodeUI Survival Permission
    default: op
  gamemodeui.use.adventure:
    description: STogkGamemodeUI Adventure Permission
    default: op
  gamemodeui.use.spectator:
    description: STogkGamemodeUI Spectator Permission
    default: op
